id: I5F33F545
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T22:12:52+00:00'
last_modified: '2022-06-07T12:40:56.356140+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W21027
  title: གསུང་འབུམ། བློ་བཟང་ཆོས་འབྱོར་ལྷུན་གྲུབ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    F15E:
      image_group_id: I3039
      title: ''
      total_pages: 566
      order: 1
      base_file: F15E.txt
    8BC7:
      image_group_id: I3040
      title: ''
      total_pages: 528
      order: 2
      base_file: 8BC7.txt
    E3CE:
      image_group_id: I3041
      title: ''
      total_pages: 562
      order: 3
      base_file: E3CE.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
