id: I5F33F545
legacy_id: P000694
ocr_import_info:
  bdrc_scan_id: W21027
  source: bdrc
  ocr_info:
    timestamp: '2020-03-29T22:09:24'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-01T13:54:16.857660+00:00'
last_modified: 2022-09-01 21:54:58.705033
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W21027
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW21027
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། བློ་བཟང་ཆོས་འབྱོར་ལྷུན་གྲུབ།
  author: རོང་ཐ་ཆེ་ཚང ༠༤་བློ་བཟང་ཆོས་འབྱོར་ལྷུན་གྲུབ།
statistics:
  ocr_word_mean_confidence_index: 0.6764556470454742
  ocr_word_median_confidence_index: 0.7200000286102295
quality: null
bases:
  I3039:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3039
      total_pages: 566
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3039.txt
    statistics:
      ocr_word_median_confidence_index: 0.7300000190734863
      ocr_word_mean_confidence_index: 0.6797026990260211
    legacy_id: v001
  I3041:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3041
      total_pages: 562
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I3041.txt
    statistics:
      ocr_word_median_confidence_index: 0.7200000286102295
      ocr_word_mean_confidence_index: 0.6771491571284557
    legacy_id: v003
  I3040:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3040
      total_pages: 528
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I3040.txt
    statistics:
      ocr_word_median_confidence_index: 0.7200000286102295
      ocr_word_mean_confidence_index: 0.6729824727466718
    legacy_id: v002
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
